### ISSUE TITLE
Anyone have the pickle file for the model

### ISSUE THREAD

**Issue by prudhvish11** [Jaydeep2401/DeTox#2]
My laptop is a very old model.So please anyone has the pickle file for the model please share with me.
email:prudhvish11@gmail.com

**Comment by jaydeepjethwa** [comment]
Hi @prudhvish11, here's the pickle file you are looking for.
[Fine Tuned Toxicity Detection Model](https://mega.nz/file/ojMDCQyK#m-mTe4VsldWhgrP4qWPrX3GqvgdTQaELqytXKiP3ryg)

**Comment by prudhvish11** [comment]
Thank You @jaydeepjethwa
